server:
  port: 8080
  startDelay: 0
  shutdownDelay: 0
health:
  status: 202
  body: "I am Fine"
  delay: 1
readiness:
  status: 200
  body: "OK"
  delay: 1
resources:
  cpu:
    target: 1
    step: 0.1
    interval: 5
  memory:
    target: 1G
    step: 100M
    interval: 5
  storage:
    target: 1G
    step: 100M
    interval: 5
